version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  web:
    container_name: servak
    image: serverviewya:latest
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - mynetwork  # Имя пользовательской сети
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - mynetwork  # Имя пользовательской сети


# encoding: utf-8    
